### ISSUE TITLE
Various issues -- I only get a sbcl and ecl working on linux and mac

### ISSUE THREAD

**Issue by simendsjo** [40ants/setup-lisp#24]
I'm developing a small library that I'd like to be portable across several implementations.

The library itself doesn't have any dependencies, so it should be fairly portable.

The test project depends on str, lisp-unit2 and sijo-doctest.

But unfortunately, it seems I only get sbcl-bin working on ubuntu-latest and macos-latest.

- windows-latest, sbcl-bin: Tests isn't actually, but everything is green (https://github.com/simendsjo/sijo-version/actions/runs/8207665322/job/22449443638)
- windows-latest, ccl-bin: ccl-bin/system does not exist.stop.
- ubuntu-latest, ccl-bin: Error: Invalid pathname component :HOME (https://github.com/simendsjo/sijo-version/actions/runs/8207847577/job/22450025143)
- macos-latest, ccl-bin: Error: Invalid pathname component :HOME (https://github.com/simendsjo/sijo-version/actions/runs/8207847577/job/22450025421)
- windows-latest, ecl: ecl/system does not exist.stop. (https://github.com/simendsjo/sijo-version/actions/runs/8207945773/job/22450316053)
- ubuntu-latest, ecl: :HOME is not of type SEQUENCE. (https://github.com/simendsjo/sijo-version/actions/runs/8207998730/job/22450476024)
- macos-latest, ecl: :HOME is not of type SEQUENCE. (https://github.com/simendsjo/sijo-version/actions/runs/8207998730/job/22450476269)
- ubuntu-latest, abcl-bin: Unsupported directory component HOME. (https://github.com/simendsjo/sijo-version/actions/runs/8208066035/job/22450691213)
- windows-latest, abcl-bin: abcl-bin/system does not exist.stop. (https://github.com/simendsjo/sijo-version/actions/runs/8208066035/job/22450783997)
- macos-latest, abcl-bin: Unsupported directory component HOME. (https://github.com/simendsjo/sijo-version/actions/runs/8208099990/job/22450796113)
- windows-latest, clasp-bin: clasp-bin/system does not exist.stop. (https://github.com/simendsjo/sijo-version/actions/runs/8208162293/job/22450983197)
- ... I dropped testing the rest.

Some are also reported as green even though there's errors raised.

Heres the workflow I tested

```yaml
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        lisp:
          - sbcl-bin
          - ccl-bin
          - ecl
          - abcl-bin
          - clasp-bin
          - cmu-bin
          - clisp-head
    runs-on: ${{ matrix.os }}
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v4
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: sijo-version/tests
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: sijo-version
```
