### ISSUE TITLE
Many implementation fails to build on Windows

### ISSUE THREAD

**Issue by svetlyak40wt** [40ants/setup-lisp#27]
For these implementations:

- ccl-bin
- clisp-head
- ecl
- abcl-bin
- clasp-bin
- cmu-bin

attempt to update quicklisp dists tells something like that:

```
Run # The parent workflow might have caching enabled for Roswell and all
  # The parent workflow might have caching enabled for Roswell and all
  # the other Lisp files in general, so it's better to tell Quicklisp
  # to update all its dists.
  ros -e "(ql:update-all-dists :prompt nil)"
  shell: D:\a\_temp\setup-msys2\lispsh.CMD -eo pipefail {0}
  env:
    LISP: ccl-bin
    MSYSTEM: MINGW64
    MSYSCON: Stop-Roswell-From-Installing-Msys2
ccl-bin/system does not exist.stop.
```
